# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '//SERVER-3D/Project/lib/setup/maya/maya_scripts_rfm4/LGT/ui/addCRCloc_test.ui'
#
# Created: Tue Nov 10 16:18:33 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Lighter_Tools(object):
    def setupUi(self, Lighter_Tools):
        Lighter_Tools.setObjectName(_fromUtf8("Lighter_Tools"))
        Lighter_Tools.resize(372, 847)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget_2 = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget_2.setAutoFillBackground(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.Tools = QtGui.QWidget()
        self.Tools.setAutoFillBackground(True)
        self.Tools.setObjectName(_fromUtf8("Tools"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.Tools)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setMargin(2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.groupBox_3 = QtGui.QGroupBox(self.Tools)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setMargin(2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.render_char_build_button = QtGui.QPushButton(self.groupBox_3)
        self.render_char_build_button.setObjectName(_fromUtf8("render_char_build_button"))
        self.verticalLayout_10.addWidget(self.render_char_build_button)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.copy_uv_checkBox = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copy_uv_checkBox.sizePolicy().hasHeightForWidth())
        self.copy_uv_checkBox.setSizePolicy(sizePolicy)
        self.copy_uv_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.copy_uv_checkBox.setChecked(True)
        self.copy_uv_checkBox.setObjectName(_fromUtf8("copy_uv_checkBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.copy_uv_checkBox)
        self.search_by_shape_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.search_by_shape_checkBox.setChecked(False)
        self.search_by_shape_checkBox.setObjectName(_fromUtf8("search_by_shape_checkBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.search_by_shape_checkBox)
        self.create_sets_checkBox = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_sets_checkBox.sizePolicy().hasHeightForWidth())
        self.create_sets_checkBox.setSizePolicy(sizePolicy)
        self.create_sets_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.create_sets_checkBox.setChecked(True)
        self.create_sets_checkBox.setObjectName(_fromUtf8("create_sets_checkBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.create_sets_checkBox)
        self.search_by_topology_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.search_by_topology_checkBox.setObjectName(_fromUtf8("search_by_topology_checkBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.search_by_topology_checkBox)
        self.delete_history_checkBox = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_history_checkBox.sizePolicy().hasHeightForWidth())
        self.delete_history_checkBox.setSizePolicy(sizePolicy)
        self.delete_history_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.delete_history_checkBox.setChecked(True)
        self.delete_history_checkBox.setObjectName(_fromUtf8("delete_history_checkBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.delete_history_checkBox)
        spacerItem = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout.setItem(2, QtGui.QFormLayout.FieldRole, spacerItem)
        self.verticalLayout_10.addLayout(self.formLayout)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.tabWidget_2.addTab(self.Tools, _fromUtf8(""))
        self.Shave_control = QtGui.QWidget()
        self.Shave_control.setEnabled(False)
        self.Shave_control.setAutoFillBackground(True)
        self.Shave_control.setObjectName(_fromUtf8("Shave_control"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Shave_control)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.objectScrollListLong = QtGui.QListWidget(self.Shave_control)
        self.objectScrollListLong.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objectScrollListLong.sizePolicy().hasHeightForWidth())
        self.objectScrollListLong.setSizePolicy(sizePolicy)
        self.objectScrollListLong.setMinimumSize(QtCore.QSize(0, 0))
        self.objectScrollListLong.setMaximumSize(QtCore.QSize(0, 0))
        self.objectScrollListLong.setFrameShape(QtGui.QFrame.NoFrame)
        self.objectScrollListLong.setLineWidth(0)
        self.objectScrollListLong.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.objectScrollListLong.setObjectName(_fromUtf8("objectScrollListLong"))
        self.verticalLayout_4.addWidget(self.objectScrollListLong)
        self.SetupCharacter = QtGui.QGroupBox(self.Shave_control)
        self.SetupCharacter.setFlat(False)
        self.SetupCharacter.setCheckable(False)
        self.SetupCharacter.setObjectName(_fromUtf8("SetupCharacter"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.SetupCharacter)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.SetupCharacter)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.widget = QtGui.QWidget(self.SetupCharacter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setMargin(2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.reloadObjectsButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reloadObjectsButton.sizePolicy().hasHeightForWidth())
        self.reloadObjectsButton.setSizePolicy(sizePolicy)
        self.reloadObjectsButton.setObjectName(_fromUtf8("reloadObjectsButton"))
        self.horizontalLayout_4.addWidget(self.reloadObjectsButton)
        self.selectObjectButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectObjectButton.sizePolicy().hasHeightForWidth())
        self.selectObjectButton.setSizePolicy(sizePolicy)
        self.selectObjectButton.setObjectName(_fromUtf8("selectObjectButton"))
        self.horizontalLayout_4.addWidget(self.selectObjectButton)
        self.syncSelectCheckBox = QtGui.QCheckBox(self.widget)
        self.syncSelectCheckBox.setChecked(True)
        self.syncSelectCheckBox.setObjectName(_fromUtf8("syncSelectCheckBox"))
        self.horizontalLayout_4.addWidget(self.syncSelectCheckBox)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_4.addWidget(self.SetupCharacter)
        self.addControlGroupBox = QtGui.QGroupBox(self.Shave_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addControlGroupBox.sizePolicy().hasHeightForWidth())
        self.addControlGroupBox.setSizePolicy(sizePolicy)
        self.addControlGroupBox.setAutoFillBackground(True)
        self.addControlGroupBox.setObjectName(_fromUtf8("addControlGroupBox"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.addControlGroupBox)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setMargin(2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.shaveControlTab = QtGui.QTabWidget(self.addControlGroupBox)
        self.shaveControlTab.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shaveControlTab.sizePolicy().hasHeightForWidth())
        self.shaveControlTab.setSizePolicy(sizePolicy)
        self.shaveControlTab.setAutoFillBackground(True)
        self.shaveControlTab.setObjectName(_fromUtf8("shaveControlTab"))
        self.contolShahveTab = QtGui.QWidget()
        self.contolShahveTab.setAutoFillBackground(True)
        self.contolShahveTab.setObjectName(_fromUtf8("contolShahveTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.contolShahveTab)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setMargin(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalWidget = QtGui.QWidget(self.contolShahveTab)
        self.horizontalWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalWidget.setAutoFillBackground(False)
        self.horizontalWidget.setObjectName(_fromUtf8("horizontalWidget"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setMargin(2)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.CreateShaveControl = QtGui.QPushButton(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateShaveControl.sizePolicy().hasHeightForWidth())
        self.CreateShaveControl.setSizePolicy(sizePolicy)
        self.CreateShaveControl.setMinimumSize(QtCore.QSize(80, 0))
        self.CreateShaveControl.setObjectName(_fromUtf8("CreateShaveControl"))
        self.horizontalLayout_12.addWidget(self.CreateShaveControl)
        self.removeShaveControl = QtGui.QPushButton(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeShaveControl.sizePolicy().hasHeightForWidth())
        self.removeShaveControl.setSizePolicy(sizePolicy)
        self.removeShaveControl.setMinimumSize(QtCore.QSize(80, 0))
        self.removeShaveControl.setObjectName(_fromUtf8("removeShaveControl"))
        self.horizontalLayout_12.addWidget(self.removeShaveControl)
        self.aplyShaveControl = QtGui.QPushButton(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aplyShaveControl.sizePolicy().hasHeightForWidth())
        self.aplyShaveControl.setSizePolicy(sizePolicy)
        self.aplyShaveControl.setMinimumSize(QtCore.QSize(80, 0))
        self.aplyShaveControl.setObjectName(_fromUtf8("aplyShaveControl"))
        self.horizontalLayout_12.addWidget(self.aplyShaveControl)
        self.verticalLayout_3.addWidget(self.horizontalWidget)
        self.Layout_Qw = QtGui.QWidget(self.contolShahveTab)
        self.Layout_Qw.setObjectName(_fromUtf8("Layout_Qw"))
        self.Layout_Q = QtGui.QHBoxLayout(self.Layout_Qw)
        self.Layout_Q.setSpacing(2)
        self.Layout_Q.setMargin(2)
        self.Layout_Q.setMargin(0)
        self.Layout_Q.setObjectName(_fromUtf8("Layout_Q"))
        self.label_2 = QtGui.QLabel(self.Layout_Qw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Layout_Q.addWidget(self.label_2)
        self.ShaveQuality = QtGui.QSlider(self.Layout_Qw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShaveQuality.sizePolicy().hasHeightForWidth())
        self.ShaveQuality.setSizePolicy(sizePolicy)
        self.ShaveQuality.setMinimumSize(QtCore.QSize(150, 20))
        self.ShaveQuality.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ShaveQuality.setMinimum(-10)
        self.ShaveQuality.setMaximum(10)
        self.ShaveQuality.setProperty("value", 0)
        self.ShaveQuality.setOrientation(QtCore.Qt.Horizontal)
        self.ShaveQuality.setTickPosition(QtGui.QSlider.TicksAbove)
        self.ShaveQuality.setTickInterval(10)
        self.ShaveQuality.setObjectName(_fromUtf8("ShaveQuality"))
        self.Layout_Q.addWidget(self.ShaveQuality)
        self.spinBox = QtGui.QSpinBox(self.Layout_Qw)
        self.spinBox.setMinimum(-10)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.Layout_Q.addWidget(self.spinBox)
        self.verticalLayout_3.addWidget(self.Layout_Qw)
        self.Layout_Tw = QtGui.QWidget(self.contolShahveTab)
        self.Layout_Tw.setObjectName(_fromUtf8("Layout_Tw"))
        self.Layout_T = QtGui.QHBoxLayout(self.Layout_Tw)
        self.Layout_T.setSpacing(2)
        self.Layout_T.setMargin(2)
        self.Layout_T.setMargin(0)
        self.Layout_T.setObjectName(_fromUtf8("Layout_T"))
        self.label_3 = QtGui.QLabel(self.Layout_Tw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Layout_T.addWidget(self.label_3)
        self.Thickness = QtGui.QSlider(self.Layout_Tw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Thickness.sizePolicy().hasHeightForWidth())
        self.Thickness.setSizePolicy(sizePolicy)
        self.Thickness.setMinimumSize(QtCore.QSize(150, 20))
        self.Thickness.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Thickness.setMinimum(-10)
        self.Thickness.setMaximum(10)
        self.Thickness.setProperty("value", 0)
        self.Thickness.setSliderPosition(0)
        self.Thickness.setOrientation(QtCore.Qt.Horizontal)
        self.Thickness.setInvertedAppearance(False)
        self.Thickness.setInvertedControls(False)
        self.Thickness.setTickPosition(QtGui.QSlider.TicksAbove)
        self.Thickness.setTickInterval(10)
        self.Thickness.setObjectName(_fromUtf8("Thickness"))
        self.Layout_T.addWidget(self.Thickness)
        self.spinBox_2 = QtGui.QSpinBox(self.Layout_Tw)
        self.spinBox_2.setMinimum(-10)
        self.spinBox_2.setMaximum(10)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.Layout_T.addWidget(self.spinBox_2)
        self.verticalLayout_3.addWidget(self.Layout_Tw)
        self.widget1 = QtGui.QWidget(self.contolShahveTab)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setMargin(2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.affectSegmet = QtGui.QCheckBox(self.widget1)
        self.affectSegmet.setChecked(False)
        self.affectSegmet.setObjectName(_fromUtf8("affectSegmet"))
        self.horizontalLayout_6.addWidget(self.affectSegmet)
        self.verticalLayout_3.addWidget(self.widget1)
        self.shaveControlTab.addTab(self.contolShahveTab, _fromUtf8(""))
        self.contolShaderTab = QtGui.QWidget()
        self.contolShaderTab.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contolShaderTab.sizePolicy().hasHeightForWidth())
        self.contolShaderTab.setSizePolicy(sizePolicy)
        self.contolShaderTab.setAutoFillBackground(True)
        self.contolShaderTab.setObjectName(_fromUtf8("contolShaderTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.contolShaderTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalWidget_4 = QtGui.QWidget(self.contolShaderTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_4.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_4.setSizePolicy(sizePolicy)
        self.horizontalWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalWidget_4.setAutoFillBackground(False)
        self.horizontalWidget_4.setObjectName(_fromUtf8("horizontalWidget_4"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_16.setSpacing(2)
        self.horizontalLayout_16.setMargin(2)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.CreateShaveControl_4 = QtGui.QPushButton(self.horizontalWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateShaveControl_4.sizePolicy().hasHeightForWidth())
        self.CreateShaveControl_4.setSizePolicy(sizePolicy)
        self.CreateShaveControl_4.setMinimumSize(QtCore.QSize(150, 0))
        self.CreateShaveControl_4.setObjectName(_fromUtf8("CreateShaveControl_4"))
        self.horizontalLayout_16.addWidget(self.CreateShaveControl_4)
        self.removeShaveControl_5 = QtGui.QPushButton(self.horizontalWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeShaveControl_5.sizePolicy().hasHeightForWidth())
        self.removeShaveControl_5.setSizePolicy(sizePolicy)
        self.removeShaveControl_5.setMinimumSize(QtCore.QSize(150, 0))
        self.removeShaveControl_5.setObjectName(_fromUtf8("removeShaveControl_5"))
        self.horizontalLayout_16.addWidget(self.removeShaveControl_5)
        self.verticalLayout_5.addWidget(self.horizontalWidget_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.shaveControlTab.addTab(self.contolShaderTab, _fromUtf8(""))
        self.controlGeometryTab = QtGui.QWidget()
        self.controlGeometryTab.setEnabled(False)
        self.controlGeometryTab.setAutoFillBackground(True)
        self.controlGeometryTab.setObjectName(_fromUtf8("controlGeometryTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.controlGeometryTab)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setMargin(2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(20, 73, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.shaveControlTab.addTab(self.controlGeometryTab, _fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.shaveControlTab)
        self.verticalLayout_4.addWidget(self.addControlGroupBox)
        self.tabWidget_2.addTab(self.Shave_control, _fromUtf8(""))
        self.mel_tmp = QtGui.QWidget()
        self.mel_tmp.setEnabled(False)
        self.mel_tmp.setAutoFillBackground(True)
        self.mel_tmp.setObjectName(_fromUtf8("mel_tmp"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.mel_tmp)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setMargin(2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.traceShadowGroupBox = QtGui.QGroupBox(self.mel_tmp)
        self.traceShadowGroupBox.setObjectName(_fromUtf8("traceShadowGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.traceShadowGroupBox)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setMargin(2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.switchTraceShadow_On = QtGui.QPushButton(self.traceShadowGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchTraceShadow_On.sizePolicy().hasHeightForWidth())
        self.switchTraceShadow_On.setSizePolicy(sizePolicy)
        self.switchTraceShadow_On.setObjectName(_fromUtf8("switchTraceShadow_On"))
        self.horizontalLayout_2.addWidget(self.switchTraceShadow_On)
        self.switchTraceShadow_Off = QtGui.QPushButton(self.traceShadowGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchTraceShadow_Off.sizePolicy().hasHeightForWidth())
        self.switchTraceShadow_Off.setSizePolicy(sizePolicy)
        self.switchTraceShadow_Off.setObjectName(_fromUtf8("switchTraceShadow_Off"))
        self.horizontalLayout_2.addWidget(self.switchTraceShadow_Off)
        self.switchTraceShadow = QtGui.QPushButton(self.traceShadowGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchTraceShadow.sizePolicy().hasHeightForWidth())
        self.switchTraceShadow.setSizePolicy(sizePolicy)
        self.switchTraceShadow.setObjectName(_fromUtf8("switchTraceShadow"))
        self.horizontalLayout_2.addWidget(self.switchTraceShadow)
        self.verticalLayout_7.addWidget(self.traceShadowGroupBox)
        self.shadowPassGroupBox = QtGui.QGroupBox(self.mel_tmp)
        self.shadowPassGroupBox.setObjectName(_fromUtf8("shadowPassGroupBox"))
        self.shadowPassControlLay = QtGui.QHBoxLayout(self.shadowPassGroupBox)
        self.shadowPassControlLay.setSpacing(2)
        self.shadowPassControlLay.setMargin(2)
        self.shadowPassControlLay.setObjectName(_fromUtf8("shadowPassControlLay"))
        self.switchShadowPass_On = QtGui.QPushButton(self.shadowPassGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchShadowPass_On.sizePolicy().hasHeightForWidth())
        self.switchShadowPass_On.setSizePolicy(sizePolicy)
        self.switchShadowPass_On.setObjectName(_fromUtf8("switchShadowPass_On"))
        self.shadowPassControlLay.addWidget(self.switchShadowPass_On)
        self.switchShadowPass_Off = QtGui.QPushButton(self.shadowPassGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchShadowPass_Off.sizePolicy().hasHeightForWidth())
        self.switchShadowPass_Off.setSizePolicy(sizePolicy)
        self.switchShadowPass_Off.setObjectName(_fromUtf8("switchShadowPass_Off"))
        self.shadowPassControlLay.addWidget(self.switchShadowPass_Off)
        self.switchShadowPass = QtGui.QPushButton(self.shadowPassGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchShadowPass.sizePolicy().hasHeightForWidth())
        self.switchShadowPass.setSizePolicy(sizePolicy)
        self.switchShadowPass.setObjectName(_fromUtf8("switchShadowPass"))
        self.shadowPassControlLay.addWidget(self.switchShadowPass)
        self.verticalLayout_7.addWidget(self.shadowPassGroupBox)
        self.SSSGroupBox = QtGui.QGroupBox(self.mel_tmp)
        self.SSSGroupBox.setObjectName(_fromUtf8("SSSGroupBox"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.SSSGroupBox)
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setMargin(2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.switchSSS_On = QtGui.QPushButton(self.SSSGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchSSS_On.sizePolicy().hasHeightForWidth())
        self.switchSSS_On.setSizePolicy(sizePolicy)
        self.switchSSS_On.setObjectName(_fromUtf8("switchSSS_On"))
        self.horizontalLayout_9.addWidget(self.switchSSS_On)
        self.switchSSS_Off = QtGui.QPushButton(self.SSSGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchSSS_Off.sizePolicy().hasHeightForWidth())
        self.switchSSS_Off.setSizePolicy(sizePolicy)
        self.switchSSS_Off.setObjectName(_fromUtf8("switchSSS_Off"))
        self.horizontalLayout_9.addWidget(self.switchSSS_Off)
        self.switchSSS_reuse = QtGui.QPushButton(self.SSSGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchSSS_reuse.sizePolicy().hasHeightForWidth())
        self.switchSSS_reuse.setSizePolicy(sizePolicy)
        self.switchSSS_reuse.setObjectName(_fromUtf8("switchSSS_reuse"))
        self.horizontalLayout_9.addWidget(self.switchSSS_reuse)
        self.verticalLayout_7.addWidget(self.SSSGroupBox)
        self.renderPlaneSetupBox = QtGui.QGroupBox(self.mel_tmp)
        self.renderPlaneSetupBox.setObjectName(_fromUtf8("renderPlaneSetupBox"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.renderPlaneSetupBox)
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setMargin(2)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.nearRenderPlaneButton = QtGui.QPushButton(self.renderPlaneSetupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nearRenderPlaneButton.sizePolicy().hasHeightForWidth())
        self.nearRenderPlaneButton.setSizePolicy(sizePolicy)
        self.nearRenderPlaneButton.setObjectName(_fromUtf8("nearRenderPlaneButton"))
        self.horizontalLayout_13.addWidget(self.nearRenderPlaneButton)
        self.midRenderPlaneButton = QtGui.QPushButton(self.renderPlaneSetupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midRenderPlaneButton.sizePolicy().hasHeightForWidth())
        self.midRenderPlaneButton.setSizePolicy(sizePolicy)
        self.midRenderPlaneButton.setObjectName(_fromUtf8("midRenderPlaneButton"))
        self.horizontalLayout_13.addWidget(self.midRenderPlaneButton)
        self.farRenderPlaneButton = QtGui.QPushButton(self.renderPlaneSetupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.farRenderPlaneButton.sizePolicy().hasHeightForWidth())
        self.farRenderPlaneButton.setSizePolicy(sizePolicy)
        self.farRenderPlaneButton.setObjectName(_fromUtf8("farRenderPlaneButton"))
        self.horizontalLayout_13.addWidget(self.farRenderPlaneButton)
        self.verticalLayout_7.addWidget(self.renderPlaneSetupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.mel_tmp)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setMargin(2)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.movePivotsButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movePivotsButton.sizePolicy().hasHeightForWidth())
        self.movePivotsButton.setSizePolicy(sizePolicy)
        self.movePivotsButton.setObjectName(_fromUtf8("movePivotsButton"))
        self.horizontalLayout_10.addWidget(self.movePivotsButton)
        self.movePivotsButton_3 = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movePivotsButton_3.sizePolicy().hasHeightForWidth())
        self.movePivotsButton_3.setSizePolicy(sizePolicy)
        self.movePivotsButton_3.setObjectName(_fromUtf8("movePivotsButton_3"))
        self.horizontalLayout_10.addWidget(self.movePivotsButton_3)
        self.movePivotsButton_2 = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movePivotsButton_2.sizePolicy().hasHeightForWidth())
        self.movePivotsButton_2.setSizePolicy(sizePolicy)
        self.movePivotsButton_2.setObjectName(_fromUtf8("movePivotsButton_2"))
        self.horizontalLayout_10.addWidget(self.movePivotsButton_2)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.mel_tmp)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setMargin(2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_8.addWidget(self.checkBox)
        self.horizontalWidget_2 = QtGui.QWidget(self.groupBox)
        self.horizontalWidget_2.setObjectName(_fromUtf8("horizontalWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.parentInSystemButton = QtGui.QPushButton(self.horizontalWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentInSystemButton.sizePolicy().hasHeightForWidth())
        self.parentInSystemButton.setSizePolicy(sizePolicy)
        self.parentInSystemButton.setObjectName(_fromUtf8("parentInSystemButton"))
        self.horizontalLayout.addWidget(self.parentInSystemButton)
        self.parentAnmGPUButton = QtGui.QPushButton(self.horizontalWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentAnmGPUButton.sizePolicy().hasHeightForWidth())
        self.parentAnmGPUButton.setSizePolicy(sizePolicy)
        self.parentAnmGPUButton.setObjectName(_fromUtf8("parentAnmGPUButton"))
        self.horizontalLayout.addWidget(self.parentAnmGPUButton)
        self.verticalLayout_8.addWidget(self.horizontalWidget_2)
        self.horizontalWidget_3 = QtGui.QWidget(self.groupBox)
        self.horizontalWidget_3.setObjectName(_fromUtf8("horizontalWidget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.getRotateButton = QtGui.QPushButton(self.horizontalWidget_3)
        self.getRotateButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.getRotateButton.setObjectName(_fromUtf8("getRotateButton"))
        self.horizontalLayout_5.addWidget(self.getRotateButton)
        self.fixRotateIntLayout = QtGui.QWidget(self.horizontalWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixRotateIntLayout.sizePolicy().hasHeightForWidth())
        self.fixRotateIntLayout.setSizePolicy(sizePolicy)
        self.fixRotateIntLayout.setMinimumSize(QtCore.QSize(0, 20))
        self.fixRotateIntLayout.setMaximumSize(QtCore.QSize(16777215, 18))
        self.fixRotateIntLayout.setObjectName(_fromUtf8("fixRotateIntLayout"))
        self.fixRotateIntLay = QtGui.QHBoxLayout(self.fixRotateIntLayout)
        self.fixRotateIntLay.setSpacing(1)
        self.fixRotateIntLay.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.fixRotateIntLay.setMargin(1)
        self.fixRotateIntLay.setMargin(0)
        self.fixRotateIntLay.setObjectName(_fromUtf8("fixRotateIntLay"))
        self.horizontalLayout_5.addWidget(self.fixRotateIntLayout)
        self.fixRotateCheckBox = QtGui.QCheckBox(self.horizontalWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixRotateCheckBox.sizePolicy().hasHeightForWidth())
        self.fixRotateCheckBox.setSizePolicy(sizePolicy)
        self.fixRotateCheckBox.setMinimumSize(QtCore.QSize(90, 0))
        self.fixRotateCheckBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.fixRotateCheckBox.setObjectName(_fromUtf8("fixRotateCheckBox"))
        self.horizontalLayout_5.addWidget(self.fixRotateCheckBox)
        self.verticalLayout_8.addWidget(self.horizontalWidget_3)
        self.horizontalWidget_5 = QtGui.QWidget(self.groupBox)
        self.horizontalWidget_5.setObjectName(_fromUtf8("horizontalWidget_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalWidget_5)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setMargin(1)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.getTranslateButton = QtGui.QPushButton(self.horizontalWidget_5)
        self.getTranslateButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.getTranslateButton.setObjectName(_fromUtf8("getTranslateButton"))
        self.horizontalLayout_11.addWidget(self.getTranslateButton)
        self.fixTranslateLayout = QtGui.QWidget(self.horizontalWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixTranslateLayout.sizePolicy().hasHeightForWidth())
        self.fixTranslateLayout.setSizePolicy(sizePolicy)
        self.fixTranslateLayout.setMinimumSize(QtCore.QSize(0, 20))
        self.fixTranslateLayout.setMaximumSize(QtCore.QSize(16777215, 18))
        self.fixTranslateLayout.setObjectName(_fromUtf8("fixTranslateLayout"))
        self.fixTranslateLay = QtGui.QHBoxLayout(self.fixTranslateLayout)
        self.fixTranslateLay.setSpacing(1)
        self.fixTranslateLay.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.fixTranslateLay.setMargin(1)
        self.fixTranslateLay.setMargin(0)
        self.fixTranslateLay.setObjectName(_fromUtf8("fixTranslateLay"))
        self.horizontalLayout_11.addWidget(self.fixTranslateLayout)
        self.fixTranslateCheckBox = QtGui.QCheckBox(self.horizontalWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixTranslateCheckBox.sizePolicy().hasHeightForWidth())
        self.fixTranslateCheckBox.setSizePolicy(sizePolicy)
        self.fixTranslateCheckBox.setMinimumSize(QtCore.QSize(90, 0))
        self.fixTranslateCheckBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.fixTranslateCheckBox.setObjectName(_fromUtf8("fixTranslateCheckBox"))
        self.horizontalLayout_11.addWidget(self.fixTranslateCheckBox)
        self.verticalLayout_8.addWidget(self.horizontalWidget_5)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.mel_tmp)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setMargin(2)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.converGpuAbcButton = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.converGpuAbcButton.sizePolicy().hasHeightForWidth())
        self.converGpuAbcButton.setSizePolicy(sizePolicy)
        self.converGpuAbcButton.setObjectName(_fromUtf8("converGpuAbcButton"))
        self.verticalLayout_11.addWidget(self.converGpuAbcButton)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.tabWidget_2.addTab(self.mel_tmp, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_2)
        Lighter_Tools.setWidget(self.dockWidgetContents)

        self.retranslateUi(Lighter_Tools)
        self.tabWidget_2.setCurrentIndex(0)
        self.shaveControlTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Lighter_Tools)

    def retranslateUi(self, Lighter_Tools):
        Lighter_Tools.setWindowTitle(QtGui.QApplication.translate("Lighter_Tools", "Lighter Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.Tools.setToolTip(QtGui.QApplication.translate("Lighter_Tools", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Lighter_Tools", "Copy slim shaders, user attributs and UV", None, QtGui.QApplication.UnicodeUTF8))
        self.render_char_build_button.setText(QtGui.QApplication.translate("Lighter_Tools", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_uv_checkBox.setText(QtGui.QApplication.translate("Lighter_Tools", "Copy UV", None, QtGui.QApplication.UnicodeUTF8))
        self.search_by_shape_checkBox.setText(QtGui.QApplication.translate("Lighter_Tools", "Search by shape name", None, QtGui.QApplication.UnicodeUTF8))
        self.create_sets_checkBox.setText(QtGui.QApplication.translate("Lighter_Tools", "Create sets", None, QtGui.QApplication.UnicodeUTF8))
        self.search_by_topology_checkBox.setText(QtGui.QApplication.translate("Lighter_Tools", "Search by topology", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_history_checkBox.setText(QtGui.QApplication.translate("Lighter_Tools", "Delete history", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Tools), QtGui.QApplication.translate("Lighter_Tools", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.Shave_control.setToolTip(QtGui.QApplication.translate("Lighter_Tools", "CRC", None, QtGui.QApplication.UnicodeUTF8))
        self.SetupCharacter.setTitle(QtGui.QApplication.translate("Lighter_Tools", "Select object with control or add control on object", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Lighter_Tools", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Lighter_Tools", "Thickness", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Lighter_Tools", "Segments", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadObjectsButton.setStatusTip(QtGui.QApplication.translate("Lighter_Tools", "Reload object in View", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadObjectsButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadObjectsButton.setProperty("-command", QtGui.QApplication.translate("Lighter_Tools", "updateCRCObjectsInScene", None, QtGui.QApplication.UnicodeUTF8))
        self.selectObjectButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.selectObjectButton.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "selectCRCObject", None, QtGui.QApplication.UnicodeUTF8))
        self.syncSelectCheckBox.setText(QtGui.QApplication.translate("Lighter_Tools", "Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.addControlGroupBox.setTitle(QtGui.QApplication.translate("Lighter_Tools", "Add control on object from list and set quality", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateShaveControl.setText(QtGui.QApplication.translate("Lighter_Tools", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateShaveControl.setProperty("-command", QtGui.QApplication.translate("Lighter_Tools", "addCRCloc", None, QtGui.QApplication.UnicodeUTF8))
        self.removeShaveControl.setText(QtGui.QApplication.translate("Lighter_Tools", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.removeShaveControl.setProperty("-command", QtGui.QApplication.translate("Lighter_Tools", "\"removeCRCloc 1\"", None, QtGui.QApplication.UnicodeUTF8))
        self.aplyShaveControl.setText(QtGui.QApplication.translate("Lighter_Tools", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.aplyShaveControl.setProperty("-command", QtGui.QApplication.translate("Lighter_Tools", "\"removeCRCloc 0\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Lighter_Tools", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.ShaveQuality.setProperty("-cc", QtGui.QApplication.translate("Lighter_Tools", "\"setCRCAttr ShaveQuality set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ShaveQuality.setProperty("-dc", QtGui.QApplication.translate("Lighter_Tools", "\"setCRCAttr ShaveQuality set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Lighter_Tools", "Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.Thickness.setProperty("-cc", QtGui.QApplication.translate("Lighter_Tools", "\"setCRCAttr Thickness set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.Thickness.setProperty("-dc", QtGui.QApplication.translate("Lighter_Tools", "\"setCRCAttr Thickness set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.affectSegmet.setText(QtGui.QApplication.translate("Lighter_Tools", "Affect On Segments", None, QtGui.QApplication.UnicodeUTF8))
        self.affectSegmet.setProperty("-cc", QtGui.QApplication.translate("Lighter_Tools", "affectCRCSegmet", None, QtGui.QApplication.UnicodeUTF8))
        self.shaveControlTab.setTabText(self.shaveControlTab.indexOf(self.contolShahveTab), QtGui.QApplication.translate("Lighter_Tools", "Shave", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateShaveControl_4.setText(QtGui.QApplication.translate("Lighter_Tools", "Add Shave Control", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateShaveControl_4.setProperty("-command", QtGui.QApplication.translate("Lighter_Tools", "addCRCloc", None, QtGui.QApplication.UnicodeUTF8))
        self.removeShaveControl_5.setText(QtGui.QApplication.translate("Lighter_Tools", "Remove Shave Control", None, QtGui.QApplication.UnicodeUTF8))
        self.removeShaveControl_5.setProperty("-command", QtGui.QApplication.translate("Lighter_Tools", "removeCRCloc", None, QtGui.QApplication.UnicodeUTF8))
        self.shaveControlTab.setTabText(self.shaveControlTab.indexOf(self.contolShaderTab), QtGui.QApplication.translate("Lighter_Tools", "Shader", None, QtGui.QApplication.UnicodeUTF8))
        self.shaveControlTab.setTabText(self.shaveControlTab.indexOf(self.controlGeometryTab), QtGui.QApplication.translate("Lighter_Tools", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Shave_control), QtGui.QApplication.translate("Lighter_Tools", "Shave control", None, QtGui.QApplication.UnicodeUTF8))
        self.traceShadowGroupBox.setTitle(QtGui.QApplication.translate("Lighter_Tools", "Trace Shadow (for selected light, or for all light). CTRL+Click select light", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow_On.setText(QtGui.QApplication.translate("Lighter_Tools", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow_On.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"switchTraceShadow 1 0\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow_Off.setText(QtGui.QApplication.translate("Lighter_Tools", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow_Off.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"switchTraceShadow 0 0\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow.setText(QtGui.QApplication.translate("Lighter_Tools", "Switch ", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"switchTraceShadow 2 0\"", None, QtGui.QApplication.UnicodeUTF8))
        self.shadowPassGroupBox.setTitle(QtGui.QApplication.translate("Lighter_Tools", "Shadow Pass (for selected light, or for all pass). CTRL+Click select light", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass_On.setText(QtGui.QApplication.translate("Lighter_Tools", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass_On.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"prmanPassComputeControl 1 shadow\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass_Off.setText(QtGui.QApplication.translate("Lighter_Tools", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass_Off.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"prmanPassComputeControl 0 shadow\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass.setText(QtGui.QApplication.translate("Lighter_Tools", "Reuse ", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"prmanPassComputeControl 2 shadow\"", None, QtGui.QApplication.UnicodeUTF8))
        self.SSSGroupBox.setTitle(QtGui.QApplication.translate("Lighter_Tools", "SSS Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_On.setText(QtGui.QApplication.translate("Lighter_Tools", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_On.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"prmanPassComputeControl 1 sss\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_Off.setText(QtGui.QApplication.translate("Lighter_Tools", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_Off.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"prmanPassComputeControl 0 sss\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_reuse.setText(QtGui.QApplication.translate("Lighter_Tools", "Reuse ", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_reuse.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"prmanPassComputeControl 2 sss\"", None, QtGui.QApplication.UnicodeUTF8))
        self.renderPlaneSetupBox.setTitle(QtGui.QApplication.translate("Lighter_Tools", "Render Plane setup", None, QtGui.QApplication.UnicodeUTF8))
        self.nearRenderPlaneButton.setToolTip(QtGui.QApplication.translate("Lighter_Tools", "<html><head/><body><p><span style=\" font-weight:600;\">(click)</span> - add selected object to &quot;nearRenderPlane_set&quot;</p><p><span style=\" font-weight:600;\">(shift + click</span>) - select object in &quot;nearRenderPlane_set&quot;</p><p><span style=\" font-weight:600;\">(ctrl+click)</span> - hide object in &quot;nearRenderPlane_set&quot;</p><p><span style=\" font-weight:600;\">(alt+click)</span> - remove object from &quot;nearRenderPlane_set&quot;</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.nearRenderPlaneButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Near", None, QtGui.QApplication.UnicodeUTF8))
        self.nearRenderPlaneButton.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"renderPlaneSetup nearRenderPlane_set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.midRenderPlaneButton.setToolTip(QtGui.QApplication.translate("Lighter_Tools", "<html><head/><body><p><span style=\" font-weight:600;\">(click)</span> - add selected object to &quot;midRenderPlane_set&quot;</p><p><span style=\" font-weight:600;\">(shift + click)</span> - select object in &quot;midRenderPlane_set&quot;</p><p><span style=\" font-weight:600;\">(ctrl+click)</span> - hide object in &quot;midRenderPlane_set&quot;</p><p><span style=\" font-weight:600;\">(alt+click)</span> - remove object from &quot;midRenderPlane_set&quot;</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.midRenderPlaneButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Mid", None, QtGui.QApplication.UnicodeUTF8))
        self.midRenderPlaneButton.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"renderPlaneSetup midRenderPlane_set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.farRenderPlaneButton.setToolTip(QtGui.QApplication.translate("Lighter_Tools", "<html><head/><body><p><span style=\" font-weight:600;\">(click)</span> - add selected object to &quot;farRenderPlane_set&quot;</p><p><span style=\" font-weight:600;\">(shift + click)</span> - select object in &quot;farRenderPlane_set&quot;</p><p><span style=\" font-weight:600;\">(ctrl+click)</span> - hide object in &quot;farRenderPlane_set&quot;</p><p><span style=\" font-weight:600;\">(alt+click)</span> - remove object from &quot;farRenderPlane_set&quot;</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.farRenderPlaneButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Far", None, QtGui.QApplication.UnicodeUTF8))
        self.farRenderPlaneButton.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"renderPlaneSetup farRenderPlane_set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Lighter_Tools", "Move Pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"movePivotsUI\"", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton_3.setText(QtGui.QApplication.translate("Lighter_Tools", "Bot", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton_3.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"movePivotsUI\"", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton_2.setText(QtGui.QApplication.translate("Lighter_Tools", "Pivots UI", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton_2.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"movePivotsUI\"", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Lighter_Tools", "Parent RIB on GPU cashe", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Lighter_Tools", "Instance child object", None, QtGui.QApplication.UnicodeUTF8))
        self.parentInSystemButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Parent In System", None, QtGui.QApplication.UnicodeUTF8))
        self.parentInSystemButton.setProperty("-c ", QtGui.QApplication.translate("Lighter_Tools", "\"ribParentSys\"", None, QtGui.QApplication.UnicodeUTF8))
        self.parentAnmGPUButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Parent Anm GPU", None, QtGui.QApplication.UnicodeUTF8))
        self.parentAnmGPUButton.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"int $fixRtValue = `checkBox -q -v fixRotateCheckBox`; int $fixTrValue = `checkBox -q -v fixTranslateCheckBox`; ribParentAnmGPU $fixRtValue $fixTrValue;\"", None, QtGui.QApplication.UnicodeUTF8))
        self.getRotateButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.getRotateButton.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"{string $curSel[] = `ls -sl`; float $curRt[] = `xform -q -ro $curSel`; floatField -e -v $curRt[0] fixRotateIntField_X; floatField -e -v (0 - $curRt[1]) fixRotateIntField_Y; floatField -e -v $curRt[2] fixRotateIntField_Z;}\"", None, QtGui.QApplication.UnicodeUTF8))
        self.fixRotateCheckBox.setText(QtGui.QApplication.translate("Lighter_Tools", "fixRotate", None, QtGui.QApplication.UnicodeUTF8))
        self.getTranslateButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.getTranslateButton.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"{string $curSel[] = `ls -sl`; float $curTr[] = `xform -q -t $curSel`; floatField -e -v $curTr[0] fixTranslateIntField_X; floatField -e -v $curTr[1] fixTranslateIntField_Y; floatField -e -v $curTr[2] fixTranslateIntField_Z;}\"", None, QtGui.QApplication.UnicodeUTF8))
        self.fixTranslateCheckBox.setText(QtGui.QApplication.translate("Lighter_Tools", "fixTranslate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Lighter_Tools", "Convert selected Alembic GPU cache in Alembic GEO cache", None, QtGui.QApplication.UnicodeUTF8))
        self.converGpuAbcButton.setText(QtGui.QApplication.translate("Lighter_Tools", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.converGpuAbcButton.setProperty("-c", QtGui.QApplication.translate("Lighter_Tools", "\"string $selForGpuToABC[] = `ls -sl`; for ($node in $selForGpuToABC){ convertGpuAbc $node;}\"", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.mel_tmp), QtGui.QApplication.translate("Lighter_Tools", "mel_tmp", None, QtGui.QApplication.UnicodeUTF8))

