# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:/Users/MikhailKorovkin/Documents/maya/2016/scripts/Zoidberg/ui/qtd/LTK_main_ui.ui'
#
# Created: Sun Jan 24 23:12:55 2016
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LTK(object):
    def setupUi(self, LTK):
        LTK.setObjectName("Zoidberg")
        LTK.resize(372, 790)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_2 = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget_2.setAcceptDrops(False)
        self.tabWidget_2.setAutoFillBackground(True)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.Tools = QtGui.QWidget()
        self.Tools.setAcceptDrops(True)
        self.Tools.setAutoFillBackground(True)
        self.Tools.setObjectName("Tools")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.Tools)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.dockWidget = QtGui.QDockWidget(self.Tools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMaximumSize(QtCore.QSize(524287, 170))
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.render_char_build_button = QtGui.QPushButton(self.groupBox_3)
        self.render_char_build_button.setObjectName("render_char_build_button")
        self.horizontalLayout_3.addWidget(self.render_char_build_button)
        self.print_match_pushButton = QtGui.QPushButton(self.groupBox_3)
        self.print_match_pushButton.setObjectName("print_match_pushButton")
        self.horizontalLayout_3.addWidget(self.print_match_pushButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.search_by_topology_checkBox = QtGui.QCheckBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_by_topology_checkBox.sizePolicy().hasHeightForWidth())
        self.search_by_topology_checkBox.setSizePolicy(sizePolicy)
        self.search_by_topology_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.search_by_topology_checkBox.setChecked(True)
        self.search_by_topology_checkBox.setObjectName("search_by_topology_checkBox")
        self.horizontalLayout_7.addWidget(self.search_by_topology_checkBox)
        self.search_by_shape_checkBox = QtGui.QCheckBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_by_shape_checkBox.sizePolicy().hasHeightForWidth())
        self.search_by_shape_checkBox.setSizePolicy(sizePolicy)
        self.search_by_shape_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.search_by_shape_checkBox.setChecked(True)
        self.search_by_shape_checkBox.setObjectName("search_by_shape_checkBox")
        self.horizontalLayout_7.addWidget(self.search_by_shape_checkBox)
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridWidget = QtGui.QWidget(self.groupBox_6)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridWidget)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(1)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.copy_uv_checkBox = QtGui.QCheckBox(self.gridWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copy_uv_checkBox.sizePolicy().hasHeightForWidth())
        self.copy_uv_checkBox.setSizePolicy(sizePolicy)
        self.copy_uv_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.copy_uv_checkBox.setChecked(True)
        self.copy_uv_checkBox.setObjectName("copy_uv_checkBox")
        self.gridLayout_2.addWidget(self.copy_uv_checkBox, 0, 0, 1, 1)
        self.delete_history_checkBox = QtGui.QCheckBox(self.gridWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_history_checkBox.sizePolicy().hasHeightForWidth())
        self.delete_history_checkBox.setSizePolicy(sizePolicy)
        self.delete_history_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.delete_history_checkBox.setChecked(True)
        self.delete_history_checkBox.setObjectName("delete_history_checkBox")
        self.gridLayout_2.addWidget(self.delete_history_checkBox, 3, 0, 1, 1)
        self.unlock_tr_checkBox = QtGui.QCheckBox(self.gridWidget)
        self.unlock_tr_checkBox.setChecked(True)
        self.unlock_tr_checkBox.setObjectName("unlock_tr_checkBox")
        self.gridLayout_2.addWidget(self.unlock_tr_checkBox, 5, 1, 1, 1)
        self.delete_color_sets_checkBox = QtGui.QCheckBox(self.gridWidget)
        self.delete_color_sets_checkBox.setChecked(True)
        self.delete_color_sets_checkBox.setObjectName("delete_color_sets_checkBox")
        self.gridLayout_2.addWidget(self.delete_color_sets_checkBox, 3, 1, 1, 1)
        self.create_sets_checkBox = QtGui.QCheckBox(self.gridWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_sets_checkBox.sizePolicy().hasHeightForWidth())
        self.create_sets_checkBox.setSizePolicy(sizePolicy)
        self.create_sets_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.create_sets_checkBox.setChecked(True)
        self.create_sets_checkBox.setObjectName("create_sets_checkBox")
        self.gridLayout_2.addWidget(self.create_sets_checkBox, 5, 0, 1, 1)
        self.copy_attr_checkBox = QtGui.QCheckBox(self.gridWidget)
        self.copy_attr_checkBox.setChecked(True)
        self.copy_attr_checkBox.setObjectName("copy_attr_checkBox")
        self.gridLayout_2.addWidget(self.copy_attr_checkBox, 0, 1, 1, 1)
        self.verticalLayout_14.addWidget(self.gridWidget)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        self.verticalLayout_12.addWidget(self.groupBox_3)
        self.dockWidget.setWidget(self.dockWidgetContents_3)
        self.verticalLayout_9.addWidget(self.dockWidget)
        self.dockWidget_2 = QtGui.QDockWidget(self.Tools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(245, 200))
        self.dockWidget_2.setMaximumSize(QtCore.QSize(524287, 200))
        self.dockWidget_2.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.quickSetgroupBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.quickSetgroupBox.setObjectName("quickSetgroupBox")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.quickSetgroupBox)
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.quickSetUnionpushButton = QtGui.QPushButton(self.quickSetgroupBox)
        self.quickSetUnionpushButton.setObjectName("quickSetUnionpushButton")
        self.horizontalLayout_14.addWidget(self.quickSetUnionpushButton)
        self.quickSetSubstractpushButton = QtGui.QPushButton(self.quickSetgroupBox)
        self.quickSetSubstractpushButton.setObjectName("quickSetSubstractpushButton")
        self.horizontalLayout_14.addWidget(self.quickSetSubstractpushButton)
        self.quickSetIntersectionpushButton = QtGui.QPushButton(self.quickSetgroupBox)
        self.quickSetIntersectionpushButton.setObjectName("quickSetIntersectionpushButton")
        self.horizontalLayout_14.addWidget(self.quickSetIntersectionpushButton)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.groupBoxlistWidget = QtGui.QListWidget(self.quickSetgroupBox)
        self.groupBoxlistWidget.setObjectName("groupBoxlistWidget")
        self.verticalLayout_15.addWidget(self.groupBoxlistWidget)
        self.verticalLayout_16.addWidget(self.quickSetgroupBox)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        self.verticalLayout_9.addWidget(self.dockWidget_2)
        self.attr_tools_groupBox = QtGui.QGroupBox(self.Tools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr_tools_groupBox.sizePolicy().hasHeightForWidth())
        self.attr_tools_groupBox.setSizePolicy(sizePolicy)
        self.attr_tools_groupBox.setObjectName("attr_tools_groupBox")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.attr_tools_groupBox)
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.attr_tools_verticalLayout = QtGui.QVBoxLayout()
        self.attr_tools_verticalLayout.setSpacing(2)
        self.attr_tools_verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.attr_tools_verticalLayout.setObjectName("attr_tools_verticalLayout")
        self.attr_tools_horizontalLayout = QtGui.QHBoxLayout()
        self.attr_tools_horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.attr_tools_horizontalLayout.setObjectName("attr_tools_horizontalLayout")
        self.attr_tools_del_pushButton = QtGui.QPushButton(self.attr_tools_groupBox)
        self.attr_tools_del_pushButton.setObjectName("attr_tools_del_pushButton")
        self.attr_tools_horizontalLayout.addWidget(self.attr_tools_del_pushButton)
        self.attr_tools_set_pushButton = QtGui.QPushButton(self.attr_tools_groupBox)
        self.attr_tools_set_pushButton.setObjectName("attr_tools_set_pushButton")
        self.attr_tools_horizontalLayout.addWidget(self.attr_tools_set_pushButton)
        self.attr_tools_sel_pushButton = QtGui.QPushButton(self.attr_tools_groupBox)
        self.attr_tools_sel_pushButton.setObjectName("attr_tools_sel_pushButton")
        self.attr_tools_horizontalLayout.addWidget(self.attr_tools_sel_pushButton)
        self.attr_tools_add_pushButton = QtGui.QPushButton(self.attr_tools_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr_tools_add_pushButton.sizePolicy().hasHeightForWidth())
        self.attr_tools_add_pushButton.setSizePolicy(sizePolicy)
        self.attr_tools_add_pushButton.setMinimumSize(QtCore.QSize(25, 20))
        self.attr_tools_add_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.attr_tools_add_pushButton.setObjectName("attr_tools_add_pushButton")
        self.attr_tools_horizontalLayout.addWidget(self.attr_tools_add_pushButton)
        self.attr_tools_verticalLayout.addLayout(self.attr_tools_horizontalLayout)
        self.attr_tools_set_QWidget = QtGui.QWidget(self.attr_tools_groupBox)
        self.attr_tools_set_QWidget.setEnabled(False)
        self.attr_tools_set_QWidget.setObjectName("attr_tools_set_QWidget")
        self.gridLayout = QtGui.QGridLayout(self.attr_tools_set_QWidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.attr_tools_value_label = QtGui.QLabel(self.attr_tools_set_QWidget)
        self.attr_tools_value_label.setObjectName("attr_tools_value_label")
        self.gridLayout.addWidget(self.attr_tools_value_label, 0, 1, 1, 1)
        self.attr_tools_attr_label = QtGui.QLabel(self.attr_tools_set_QWidget)
        self.attr_tools_attr_label.setObjectName("attr_tools_attr_label")
        self.gridLayout.addWidget(self.attr_tools_attr_label, 0, 0, 1, 1)
        self.attr_tools_value_lineEdit = QtGui.QLineEdit(self.attr_tools_set_QWidget)
        self.attr_tools_value_lineEdit.setText("")
        self.attr_tools_value_lineEdit.setObjectName("attr_tools_value_lineEdit")
        self.gridLayout.addWidget(self.attr_tools_value_lineEdit, 1, 1, 1, 1)
        self.attr_tools_attr_lineEdit = QtGui.QLineEdit(self.attr_tools_set_QWidget)
        self.attr_tools_attr_lineEdit.setObjectName("attr_tools_attr_lineEdit")
        self.gridLayout.addWidget(self.attr_tools_attr_lineEdit, 1, 0, 1, 1)
        self.attr_tools_verticalLayout.addWidget(self.attr_tools_set_QWidget)
        self.verticalLayout_13.addLayout(self.attr_tools_verticalLayout)
        self.verticalLayout_9.addWidget(self.attr_tools_groupBox)
        self.MELverpushButton = QtGui.QPushButton(self.Tools)
        self.MELverpushButton.setObjectName("MELverpushButton")
        self.verticalLayout_9.addWidget(self.MELverpushButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image_icon/C:/Users/korovkin_m/Pictures/dr-manhattan2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.Tools, icon, "")
        self.mel_tmp = QtGui.QWidget()
        self.mel_tmp.setEnabled(True)
        self.mel_tmp.setAutoFillBackground(True)
        self.mel_tmp.setObjectName("mel_tmp")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.mel_tmp)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.traceShadowGroupBox = QtGui.QGroupBox(self.mel_tmp)
        self.traceShadowGroupBox.setObjectName("traceShadowGroupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.traceShadowGroupBox)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.switchTraceShadow_On = QtGui.QPushButton(self.traceShadowGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchTraceShadow_On.sizePolicy().hasHeightForWidth())
        self.switchTraceShadow_On.setSizePolicy(sizePolicy)
        self.switchTraceShadow_On.setObjectName("switchTraceShadow_On")
        self.horizontalLayout_2.addWidget(self.switchTraceShadow_On)
        self.switchTraceShadow_Off = QtGui.QPushButton(self.traceShadowGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchTraceShadow_Off.sizePolicy().hasHeightForWidth())
        self.switchTraceShadow_Off.setSizePolicy(sizePolicy)
        self.switchTraceShadow_Off.setObjectName("switchTraceShadow_Off")
        self.horizontalLayout_2.addWidget(self.switchTraceShadow_Off)
        self.switchTraceShadow = QtGui.QPushButton(self.traceShadowGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchTraceShadow.sizePolicy().hasHeightForWidth())
        self.switchTraceShadow.setSizePolicy(sizePolicy)
        self.switchTraceShadow.setObjectName("switchTraceShadow")
        self.horizontalLayout_2.addWidget(self.switchTraceShadow)
        self.verticalLayout_7.addWidget(self.traceShadowGroupBox)
        self.shadowPassGroupBox = QtGui.QGroupBox(self.mel_tmp)
        self.shadowPassGroupBox.setObjectName("shadowPassGroupBox")
        self.shadowPassControlLay = QtGui.QHBoxLayout(self.shadowPassGroupBox)
        self.shadowPassControlLay.setSpacing(2)
        self.shadowPassControlLay.setContentsMargins(2, 2, 2, 2)
        self.shadowPassControlLay.setObjectName("shadowPassControlLay")
        self.switchShadowPass_On = QtGui.QPushButton(self.shadowPassGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchShadowPass_On.sizePolicy().hasHeightForWidth())
        self.switchShadowPass_On.setSizePolicy(sizePolicy)
        self.switchShadowPass_On.setObjectName("switchShadowPass_On")
        self.shadowPassControlLay.addWidget(self.switchShadowPass_On)
        self.switchShadowPass_Off = QtGui.QPushButton(self.shadowPassGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchShadowPass_Off.sizePolicy().hasHeightForWidth())
        self.switchShadowPass_Off.setSizePolicy(sizePolicy)
        self.switchShadowPass_Off.setObjectName("switchShadowPass_Off")
        self.shadowPassControlLay.addWidget(self.switchShadowPass_Off)
        self.switchShadowPass = QtGui.QPushButton(self.shadowPassGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchShadowPass.sizePolicy().hasHeightForWidth())
        self.switchShadowPass.setSizePolicy(sizePolicy)
        self.switchShadowPass.setObjectName("switchShadowPass")
        self.shadowPassControlLay.addWidget(self.switchShadowPass)
        self.verticalLayout_7.addWidget(self.shadowPassGroupBox)
        self.SSSGroupBox = QtGui.QGroupBox(self.mel_tmp)
        self.SSSGroupBox.setObjectName("SSSGroupBox")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.SSSGroupBox)
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.switchSSS_On = QtGui.QPushButton(self.SSSGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchSSS_On.sizePolicy().hasHeightForWidth())
        self.switchSSS_On.setSizePolicy(sizePolicy)
        self.switchSSS_On.setObjectName("switchSSS_On")
        self.horizontalLayout_9.addWidget(self.switchSSS_On)
        self.switchSSS_Off = QtGui.QPushButton(self.SSSGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchSSS_Off.sizePolicy().hasHeightForWidth())
        self.switchSSS_Off.setSizePolicy(sizePolicy)
        self.switchSSS_Off.setObjectName("switchSSS_Off")
        self.horizontalLayout_9.addWidget(self.switchSSS_Off)
        self.switchSSS_reuse = QtGui.QPushButton(self.SSSGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switchSSS_reuse.sizePolicy().hasHeightForWidth())
        self.switchSSS_reuse.setSizePolicy(sizePolicy)
        self.switchSSS_reuse.setObjectName("switchSSS_reuse")
        self.horizontalLayout_9.addWidget(self.switchSSS_reuse)
        self.verticalLayout_7.addWidget(self.SSSGroupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.mel_tmp)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.movePivotsButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movePivotsButton.sizePolicy().hasHeightForWidth())
        self.movePivotsButton.setSizePolicy(sizePolicy)
        self.movePivotsButton.setObjectName("movePivotsButton")
        self.horizontalLayout_10.addWidget(self.movePivotsButton)
        self.movePivotsButton_3 = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movePivotsButton_3.sizePolicy().hasHeightForWidth())
        self.movePivotsButton_3.setSizePolicy(sizePolicy)
        self.movePivotsButton_3.setObjectName("movePivotsButton_3")
        self.horizontalLayout_10.addWidget(self.movePivotsButton_3)
        self.movePivotsButton_2 = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movePivotsButton_2.sizePolicy().hasHeightForWidth())
        self.movePivotsButton_2.setSizePolicy(sizePolicy)
        self.movePivotsButton_2.setObjectName("movePivotsButton_2")
        self.horizontalLayout_10.addWidget(self.movePivotsButton_2)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.mel_tmp)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_8.addWidget(self.checkBox)
        self.horizontalWidget_2 = QtGui.QWidget(self.groupBox)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.parentInSystemButton = QtGui.QPushButton(self.horizontalWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentInSystemButton.sizePolicy().hasHeightForWidth())
        self.parentInSystemButton.setSizePolicy(sizePolicy)
        self.parentInSystemButton.setObjectName("parentInSystemButton")
        self.horizontalLayout.addWidget(self.parentInSystemButton)
        self.parentAnmGPUButton = QtGui.QPushButton(self.horizontalWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentAnmGPUButton.sizePolicy().hasHeightForWidth())
        self.parentAnmGPUButton.setSizePolicy(sizePolicy)
        self.parentAnmGPUButton.setObjectName("parentAnmGPUButton")
        self.horizontalLayout.addWidget(self.parentAnmGPUButton)
        self.verticalLayout_8.addWidget(self.horizontalWidget_2)
        self.horizontalWidget_3 = QtGui.QWidget(self.groupBox)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.getRotateButton = QtGui.QPushButton(self.horizontalWidget_3)
        self.getRotateButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.getRotateButton.setObjectName("getRotateButton")
        self.horizontalLayout_5.addWidget(self.getRotateButton)
        self.fixRotateIntLayout = QtGui.QWidget(self.horizontalWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixRotateIntLayout.sizePolicy().hasHeightForWidth())
        self.fixRotateIntLayout.setSizePolicy(sizePolicy)
        self.fixRotateIntLayout.setMinimumSize(QtCore.QSize(0, 20))
        self.fixRotateIntLayout.setMaximumSize(QtCore.QSize(16777215, 18))
        self.fixRotateIntLayout.setObjectName("fixRotateIntLayout")
        self.fixRotateIntLay = QtGui.QHBoxLayout(self.fixRotateIntLayout)
        self.fixRotateIntLay.setSpacing(1)
        self.fixRotateIntLay.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.fixRotateIntLay.setContentsMargins(1, 1, 1, 1)
        self.fixRotateIntLay.setContentsMargins(0, 0, 0, 0)
        self.fixRotateIntLay.setObjectName("fixRotateIntLay")
        self.horizontalLayout_5.addWidget(self.fixRotateIntLayout)
        self.fixRotateCheckBox = QtGui.QCheckBox(self.horizontalWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixRotateCheckBox.sizePolicy().hasHeightForWidth())
        self.fixRotateCheckBox.setSizePolicy(sizePolicy)
        self.fixRotateCheckBox.setMinimumSize(QtCore.QSize(90, 0))
        self.fixRotateCheckBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.fixRotateCheckBox.setObjectName("fixRotateCheckBox")
        self.horizontalLayout_5.addWidget(self.fixRotateCheckBox)
        self.verticalLayout_8.addWidget(self.horizontalWidget_3)
        self.horizontalWidget_5 = QtGui.QWidget(self.groupBox)
        self.horizontalWidget_5.setObjectName("horizontalWidget_5")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalWidget_5)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.getTranslateButton = QtGui.QPushButton(self.horizontalWidget_5)
        self.getTranslateButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.getTranslateButton.setObjectName("getTranslateButton")
        self.horizontalLayout_11.addWidget(self.getTranslateButton)
        self.fixTranslateLayout = QtGui.QWidget(self.horizontalWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixTranslateLayout.sizePolicy().hasHeightForWidth())
        self.fixTranslateLayout.setSizePolicy(sizePolicy)
        self.fixTranslateLayout.setMinimumSize(QtCore.QSize(0, 20))
        self.fixTranslateLayout.setMaximumSize(QtCore.QSize(16777215, 18))
        self.fixTranslateLayout.setObjectName("fixTranslateLayout")
        self.fixTranslateLay = QtGui.QHBoxLayout(self.fixTranslateLayout)
        self.fixTranslateLay.setSpacing(1)
        self.fixTranslateLay.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.fixTranslateLay.setContentsMargins(1, 1, 1, 1)
        self.fixTranslateLay.setContentsMargins(0, 0, 0, 0)
        self.fixTranslateLay.setObjectName("fixTranslateLay")
        self.horizontalLayout_11.addWidget(self.fixTranslateLayout)
        self.fixTranslateCheckBox = QtGui.QCheckBox(self.horizontalWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixTranslateCheckBox.sizePolicy().hasHeightForWidth())
        self.fixTranslateCheckBox.setSizePolicy(sizePolicy)
        self.fixTranslateCheckBox.setMinimumSize(QtCore.QSize(90, 0))
        self.fixTranslateCheckBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.fixTranslateCheckBox.setObjectName("fixTranslateCheckBox")
        self.horizontalLayout_11.addWidget(self.fixTranslateCheckBox)
        self.verticalLayout_8.addWidget(self.horizontalWidget_5)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.mel_tmp)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.converGpuAbcButton = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.converGpuAbcButton.sizePolicy().hasHeightForWidth())
        self.converGpuAbcButton.setSizePolicy(sizePolicy)
        self.converGpuAbcButton.setObjectName("converGpuAbcButton")
        self.verticalLayout_11.addWidget(self.converGpuAbcButton)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.tabWidget_2.addTab(self.mel_tmp, "")
        self.Shave_control = QtGui.QWidget()
        self.Shave_control.setEnabled(True)
        self.Shave_control.setAutoFillBackground(True)
        self.Shave_control.setObjectName("Shave_control")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Shave_control)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.objectScrollListLong = QtGui.QListWidget(self.Shave_control)
        self.objectScrollListLong.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objectScrollListLong.sizePolicy().hasHeightForWidth())
        self.objectScrollListLong.setSizePolicy(sizePolicy)
        self.objectScrollListLong.setMinimumSize(QtCore.QSize(0, 0))
        self.objectScrollListLong.setMaximumSize(QtCore.QSize(0, 0))
        self.objectScrollListLong.setFrameShape(QtGui.QFrame.NoFrame)
        self.objectScrollListLong.setLineWidth(0)
        self.objectScrollListLong.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.objectScrollListLong.setObjectName("objectScrollListLong")
        self.verticalLayout_4.addWidget(self.objectScrollListLong)
        self.SetupCharacter = QtGui.QGroupBox(self.Shave_control)
        self.SetupCharacter.setFlat(False)
        self.SetupCharacter.setCheckable(False)
        self.SetupCharacter.setObjectName("SetupCharacter")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.SetupCharacter)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtGui.QTableWidget(self.SetupCharacter)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.widget = QtGui.QWidget(self.SetupCharacter)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reloadObjectsButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reloadObjectsButton.sizePolicy().hasHeightForWidth())
        self.reloadObjectsButton.setSizePolicy(sizePolicy)
        self.reloadObjectsButton.setObjectName("reloadObjectsButton")
        self.horizontalLayout_4.addWidget(self.reloadObjectsButton)
        self.selectObjectButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectObjectButton.sizePolicy().hasHeightForWidth())
        self.selectObjectButton.setSizePolicy(sizePolicy)
        self.selectObjectButton.setObjectName("selectObjectButton")
        self.horizontalLayout_4.addWidget(self.selectObjectButton)
        self.syncSelectCheckBox = QtGui.QCheckBox(self.widget)
        self.syncSelectCheckBox.setChecked(True)
        self.syncSelectCheckBox.setObjectName("syncSelectCheckBox")
        self.horizontalLayout_4.addWidget(self.syncSelectCheckBox)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_4.addWidget(self.SetupCharacter)
        self.addControlGroupBox = QtGui.QGroupBox(self.Shave_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addControlGroupBox.sizePolicy().hasHeightForWidth())
        self.addControlGroupBox.setSizePolicy(sizePolicy)
        self.addControlGroupBox.setAutoFillBackground(True)
        self.addControlGroupBox.setObjectName("addControlGroupBox")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.addControlGroupBox)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.shaveControlTab = QtGui.QTabWidget(self.addControlGroupBox)
        self.shaveControlTab.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shaveControlTab.sizePolicy().hasHeightForWidth())
        self.shaveControlTab.setSizePolicy(sizePolicy)
        self.shaveControlTab.setAutoFillBackground(True)
        self.shaveControlTab.setObjectName("shaveControlTab")
        self.contolShahveTab = QtGui.QWidget()
        self.contolShahveTab.setAutoFillBackground(True)
        self.contolShahveTab.setObjectName("contolShahveTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.contolShahveTab)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalWidget = QtGui.QWidget(self.contolShahveTab)
        self.horizontalWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalWidget.setAutoFillBackground(False)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.CreateShaveControl = QtGui.QPushButton(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateShaveControl.sizePolicy().hasHeightForWidth())
        self.CreateShaveControl.setSizePolicy(sizePolicy)
        self.CreateShaveControl.setMinimumSize(QtCore.QSize(80, 0))
        self.CreateShaveControl.setObjectName("CreateShaveControl")
        self.horizontalLayout_12.addWidget(self.CreateShaveControl)
        self.removeShaveControl = QtGui.QPushButton(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeShaveControl.sizePolicy().hasHeightForWidth())
        self.removeShaveControl.setSizePolicy(sizePolicy)
        self.removeShaveControl.setMinimumSize(QtCore.QSize(80, 0))
        self.removeShaveControl.setObjectName("removeShaveControl")
        self.horizontalLayout_12.addWidget(self.removeShaveControl)
        self.aplyShaveControl = QtGui.QPushButton(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aplyShaveControl.sizePolicy().hasHeightForWidth())
        self.aplyShaveControl.setSizePolicy(sizePolicy)
        self.aplyShaveControl.setMinimumSize(QtCore.QSize(80, 0))
        self.aplyShaveControl.setObjectName("aplyShaveControl")
        self.horizontalLayout_12.addWidget(self.aplyShaveControl)
        self.verticalLayout_3.addWidget(self.horizontalWidget)
        self.Layout_Qw = QtGui.QWidget(self.contolShahveTab)
        self.Layout_Qw.setObjectName("Layout_Qw")
        self.Layout_Q = QtGui.QHBoxLayout(self.Layout_Qw)
        self.Layout_Q.setSpacing(2)
        self.Layout_Q.setContentsMargins(2, 2, 2, 2)
        self.Layout_Q.setContentsMargins(0, 0, 0, 0)
        self.Layout_Q.setObjectName("Layout_Q")
        self.label_2 = QtGui.QLabel(self.Layout_Qw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setObjectName("label_2")
        self.Layout_Q.addWidget(self.label_2)
        self.ShaveQuality = QtGui.QSlider(self.Layout_Qw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShaveQuality.sizePolicy().hasHeightForWidth())
        self.ShaveQuality.setSizePolicy(sizePolicy)
        self.ShaveQuality.setMinimumSize(QtCore.QSize(150, 20))
        self.ShaveQuality.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ShaveQuality.setMinimum(-10)
        self.ShaveQuality.setMaximum(10)
        self.ShaveQuality.setProperty("value", 0)
        self.ShaveQuality.setOrientation(QtCore.Qt.Horizontal)
        self.ShaveQuality.setTickPosition(QtGui.QSlider.TicksAbove)
        self.ShaveQuality.setTickInterval(10)
        self.ShaveQuality.setObjectName("ShaveQuality")
        self.Layout_Q.addWidget(self.ShaveQuality)
        self.spinBox = QtGui.QSpinBox(self.Layout_Qw)
        self.spinBox.setMinimum(-10)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.Layout_Q.addWidget(self.spinBox)
        self.verticalLayout_3.addWidget(self.Layout_Qw)
        self.Layout_Tw = QtGui.QWidget(self.contolShahveTab)
        self.Layout_Tw.setObjectName("Layout_Tw")
        self.Layout_T = QtGui.QHBoxLayout(self.Layout_Tw)
        self.Layout_T.setSpacing(2)
        self.Layout_T.setContentsMargins(2, 2, 2, 2)
        self.Layout_T.setContentsMargins(0, 0, 0, 0)
        self.Layout_T.setObjectName("Layout_T")
        self.label_3 = QtGui.QLabel(self.Layout_Tw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setObjectName("label_3")
        self.Layout_T.addWidget(self.label_3)
        self.Thickness = QtGui.QSlider(self.Layout_Tw)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Thickness.sizePolicy().hasHeightForWidth())
        self.Thickness.setSizePolicy(sizePolicy)
        self.Thickness.setMinimumSize(QtCore.QSize(150, 20))
        self.Thickness.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Thickness.setMinimum(-10)
        self.Thickness.setMaximum(10)
        self.Thickness.setProperty("value", 0)
        self.Thickness.setSliderPosition(0)
        self.Thickness.setOrientation(QtCore.Qt.Horizontal)
        self.Thickness.setInvertedAppearance(False)
        self.Thickness.setInvertedControls(False)
        self.Thickness.setTickPosition(QtGui.QSlider.TicksAbove)
        self.Thickness.setTickInterval(10)
        self.Thickness.setObjectName("Thickness")
        self.Layout_T.addWidget(self.Thickness)
        self.spinBox_2 = QtGui.QSpinBox(self.Layout_Tw)
        self.spinBox_2.setMinimum(-10)
        self.spinBox_2.setMaximum(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.Layout_T.addWidget(self.spinBox_2)
        self.verticalLayout_3.addWidget(self.Layout_Tw)
        self.widget1 = QtGui.QWidget(self.contolShahveTab)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.affectSegmet = QtGui.QCheckBox(self.widget1)
        self.affectSegmet.setChecked(False)
        self.affectSegmet.setObjectName("affectSegmet")
        self.horizontalLayout_6.addWidget(self.affectSegmet)
        self.affectSegmet_2 = QtGui.QCheckBox(self.widget1)
        self.affectSegmet_2.setChecked(False)
        self.affectSegmet_2.setObjectName("affectSegmet_2")
        self.horizontalLayout_6.addWidget(self.affectSegmet_2)
        self.verticalLayout_3.addWidget(self.widget1)
        self.shaveControlTab.addTab(self.contolShahveTab, "")
        self.contolShaderTab = QtGui.QWidget()
        self.contolShaderTab.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contolShaderTab.sizePolicy().hasHeightForWidth())
        self.contolShaderTab.setSizePolicy(sizePolicy)
        self.contolShaderTab.setAutoFillBackground(True)
        self.contolShaderTab.setObjectName("contolShaderTab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.contolShaderTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalWidget_4 = QtGui.QWidget(self.contolShaderTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_4.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_4.setSizePolicy(sizePolicy)
        self.horizontalWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalWidget_4.setAutoFillBackground(False)
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_16.setSpacing(2)
        self.horizontalLayout_16.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.CreateShaveControl_4 = QtGui.QPushButton(self.horizontalWidget_4)
        self.CreateShaveControl_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateShaveControl_4.sizePolicy().hasHeightForWidth())
        self.CreateShaveControl_4.setSizePolicy(sizePolicy)
        self.CreateShaveControl_4.setMinimumSize(QtCore.QSize(150, 0))
        self.CreateShaveControl_4.setObjectName("CreateShaveControl_4")
        self.horizontalLayout_16.addWidget(self.CreateShaveControl_4)
        self.removeShaveControl_5 = QtGui.QPushButton(self.horizontalWidget_4)
        self.removeShaveControl_5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeShaveControl_5.sizePolicy().hasHeightForWidth())
        self.removeShaveControl_5.setSizePolicy(sizePolicy)
        self.removeShaveControl_5.setMinimumSize(QtCore.QSize(150, 0))
        self.removeShaveControl_5.setObjectName("removeShaveControl_5")
        self.horizontalLayout_16.addWidget(self.removeShaveControl_5)
        self.verticalLayout_5.addWidget(self.horizontalWidget_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.shaveControlTab.addTab(self.contolShaderTab, "")
        self.controlGeometryTab = QtGui.QWidget()
        self.controlGeometryTab.setEnabled(True)
        self.controlGeometryTab.setAutoFillBackground(True)
        self.controlGeometryTab.setObjectName("controlGeometryTab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.controlGeometryTab)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem3 = QtGui.QSpacerItem(20, 73, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.shaveControlTab.addTab(self.controlGeometryTab, "")
        self.horizontalLayout_8.addWidget(self.shaveControlTab)
        self.verticalLayout_4.addWidget(self.addControlGroupBox)
        self.tabWidget_2.addTab(self.Shave_control, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        LTK.setWidget(self.dockWidgetContents)

        self.retranslateUi(LTK)
        self.tabWidget_2.setCurrentIndex(2)
        self.shaveControlTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LTK)

    def retranslateUi(self, LTK):
        LTK.setWindowTitle(QtGui.QApplication.translate("Zoidberg", "Lighter toolkit", None, QtGui.QApplication.UnicodeUTF8))
        self.Tools.setToolTip(QtGui.QApplication.translate("Zoidberg", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Zoidberg", "Copy slim shaders, user attributs and UV", None, QtGui.QApplication.UnicodeUTF8))
        self.render_char_build_button.setText(QtGui.QApplication.translate("Zoidberg", "Do", None, QtGui.QApplication.UnicodeUTF8))
        self.print_match_pushButton.setText(QtGui.QApplication.translate("Zoidberg", "Print Match", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Zoidberg", "Searching method", None, QtGui.QApplication.UnicodeUTF8))
        self.search_by_topology_checkBox.setText(QtGui.QApplication.translate("Zoidberg", "By topology", None, QtGui.QApplication.UnicodeUTF8))
        self.search_by_shape_checkBox.setText(QtGui.QApplication.translate("Zoidberg", "By shape name", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Zoidberg", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_uv_checkBox.setText(QtGui.QApplication.translate("Zoidberg", "Copy UV", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_history_checkBox.setText(QtGui.QApplication.translate("Zoidberg", "Delete history", None, QtGui.QApplication.UnicodeUTF8))
        self.unlock_tr_checkBox.setText(QtGui.QApplication.translate("Zoidberg", "Unlock transfrom", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_color_sets_checkBox.setText(QtGui.QApplication.translate("Zoidberg", "Delete color sets", None, QtGui.QApplication.UnicodeUTF8))
        self.create_sets_checkBox.setText(QtGui.QApplication.translate("Zoidberg", "Create sets", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_attr_checkBox.setText(QtGui.QApplication.translate("Zoidberg", "Copy user attr", None, QtGui.QApplication.UnicodeUTF8))
        self.quickSetgroupBox.setTitle(QtGui.QApplication.translate("Zoidberg", "Quick sets", None, QtGui.QApplication.UnicodeUTF8))
        self.quickSetUnionpushButton.setText(QtGui.QApplication.translate("Zoidberg", "Union", None, QtGui.QApplication.UnicodeUTF8))
        self.quickSetSubstractpushButton.setText(QtGui.QApplication.translate("Zoidberg", "Subtract", None, QtGui.QApplication.UnicodeUTF8))
        self.quickSetIntersectionpushButton.setText(QtGui.QApplication.translate("Zoidberg", "Intersection", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_tools_groupBox.setTitle(QtGui.QApplication.translate("Zoidberg", "Attribute tools", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_tools_del_pushButton.setText(QtGui.QApplication.translate("Zoidberg", "Delete attr", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_tools_set_pushButton.setText(QtGui.QApplication.translate("Zoidberg", "Set attr", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_tools_sel_pushButton.setText(QtGui.QApplication.translate("Zoidberg", "Select object", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_tools_add_pushButton.setText(QtGui.QApplication.translate("Zoidberg", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_tools_value_label.setText(QtGui.QApplication.translate("Zoidberg", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.attr_tools_attr_label.setText(QtGui.QApplication.translate("Zoidberg", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.MELverpushButton.setText(QtGui.QApplication.translate("Zoidberg", "Old MEL version", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Tools), QtGui.QApplication.translate("Zoidberg", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.traceShadowGroupBox.setTitle(QtGui.QApplication.translate("Zoidberg", "Trace Shadow (for selected light, or for all light). CTRL+Click select light", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow_On.setText(QtGui.QApplication.translate("Zoidberg", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow_On.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"switchTraceShadow 1 0\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow_Off.setText(QtGui.QApplication.translate("Zoidberg", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow_Off.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"switchTraceShadow 0 0\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow.setText(QtGui.QApplication.translate("Zoidberg", "Switch ", None, QtGui.QApplication.UnicodeUTF8))
        self.switchTraceShadow.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"switchTraceShadow 2 0\"", None, QtGui.QApplication.UnicodeUTF8))
        self.shadowPassGroupBox.setTitle(QtGui.QApplication.translate("Zoidberg", "Shadow Pass (for selected light, or for all pass). CTRL+Click select light", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass_On.setText(QtGui.QApplication.translate("Zoidberg", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass_On.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"prmanPassComputeControl 1 shadow\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass_Off.setText(QtGui.QApplication.translate("Zoidberg", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass_Off.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"prmanPassComputeControl 0 shadow\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass.setText(QtGui.QApplication.translate("Zoidberg", "Reuse ", None, QtGui.QApplication.UnicodeUTF8))
        self.switchShadowPass.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"prmanPassComputeControl 2 shadow\"", None, QtGui.QApplication.UnicodeUTF8))
        self.SSSGroupBox.setTitle(QtGui.QApplication.translate("Zoidberg", "SSS Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_On.setText(QtGui.QApplication.translate("Zoidberg", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_On.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"prmanPassComputeControl 1 sss\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_Off.setText(QtGui.QApplication.translate("Zoidberg", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_Off.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"prmanPassComputeControl 0 sss\"", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_reuse.setText(QtGui.QApplication.translate("Zoidberg", "Reuse ", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSSS_reuse.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"prmanPassComputeControl 2 sss\"", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Zoidberg", "Move Pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton.setText(QtGui.QApplication.translate("Zoidberg", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"movePivotsUI\"", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton_3.setText(QtGui.QApplication.translate("Zoidberg", "Bot", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton_3.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"movePivotsUI\"", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton_2.setText(QtGui.QApplication.translate("Zoidberg", "Pivots UI", None, QtGui.QApplication.UnicodeUTF8))
        self.movePivotsButton_2.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"movePivotsUI\"", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Zoidberg", "Parent RIB on GPU cashe", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Zoidberg", "Instance child object", None, QtGui.QApplication.UnicodeUTF8))
        self.parentInSystemButton.setText(QtGui.QApplication.translate("Zoidberg", "Parent In System", None, QtGui.QApplication.UnicodeUTF8))
        self.parentInSystemButton.setProperty("-c ", QtGui.QApplication.translate("Zoidberg", "\"ribParentSys\"", None, QtGui.QApplication.UnicodeUTF8))
        self.parentAnmGPUButton.setText(QtGui.QApplication.translate("Zoidberg", "Parent Anm GPU", None, QtGui.QApplication.UnicodeUTF8))
        self.parentAnmGPUButton.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"int $fixRtValue = `checkBox -q -v fixRotateCheckBox`; int $fixTrValue = `checkBox -q -v fixTranslateCheckBox`; ribParentAnmGPU $fixRtValue $fixTrValue;\"", None, QtGui.QApplication.UnicodeUTF8))
        self.getRotateButton.setText(QtGui.QApplication.translate("Zoidberg", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.getRotateButton.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"{string $curSel[] = `ls -sl`; float $curRt[] = `xform -q -ro $curSel`; floatField -e -v $curRt[0] fixRotateIntField_X; floatField -e -v (0 - $curRt[1]) fixRotateIntField_Y; floatField -e -v $curRt[2] fixRotateIntField_Z;}\"", None, QtGui.QApplication.UnicodeUTF8))
        self.fixRotateCheckBox.setText(QtGui.QApplication.translate("Zoidberg", "fixRotate", None, QtGui.QApplication.UnicodeUTF8))
        self.getTranslateButton.setText(QtGui.QApplication.translate("Zoidberg", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.getTranslateButton.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"{string $curSel[] = `ls -sl`; float $curTr[] = `xform -q -t $curSel`; floatField -e -v $curTr[0] fixTranslateIntField_X; floatField -e -v $curTr[1] fixTranslateIntField_Y; floatField -e -v $curTr[2] fixTranslateIntField_Z;}\"", None, QtGui.QApplication.UnicodeUTF8))
        self.fixTranslateCheckBox.setText(QtGui.QApplication.translate("Zoidberg", "fixTranslate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Zoidberg", "Convert selected Alembic GPU cache in Alembic GEO cache", None, QtGui.QApplication.UnicodeUTF8))
        self.converGpuAbcButton.setText(QtGui.QApplication.translate("Zoidberg", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.converGpuAbcButton.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "\"string $selForGpuToABC[] = `ls -sl`; for ($node in $selForGpuToABC){ convertGpuAbc $node;}\"", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.mel_tmp), QtGui.QApplication.translate("Zoidberg", "mel_tmp", None, QtGui.QApplication.UnicodeUTF8))
        self.Shave_control.setToolTip(QtGui.QApplication.translate("Zoidberg", "CRC", None, QtGui.QApplication.UnicodeUTF8))
        self.SetupCharacter.setTitle(QtGui.QApplication.translate("Zoidberg", "Select object with control or add control on object", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Zoidberg", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Zoidberg", "Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Zoidberg", "Segments", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadObjectsButton.setStatusTip(QtGui.QApplication.translate("Zoidberg", "Reload object in View", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadObjectsButton.setText(QtGui.QApplication.translate("Zoidberg", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadObjectsButton.setProperty("-command", QtGui.QApplication.translate("Zoidberg", "updateCRCObjectsInScene", None, QtGui.QApplication.UnicodeUTF8))
        self.selectObjectButton.setText(QtGui.QApplication.translate("Zoidberg", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.selectObjectButton.setProperty("-c", QtGui.QApplication.translate("Zoidberg", "selectCRCObject", None, QtGui.QApplication.UnicodeUTF8))
        self.syncSelectCheckBox.setText(QtGui.QApplication.translate("Zoidberg", "Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.addControlGroupBox.setTitle(QtGui.QApplication.translate("Zoidberg", "Add control on object from list and set quality", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateShaveControl.setText(QtGui.QApplication.translate("Zoidberg", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateShaveControl.setProperty("-command", QtGui.QApplication.translate("Zoidberg", "addCRCloc", None, QtGui.QApplication.UnicodeUTF8))
        self.removeShaveControl.setText(QtGui.QApplication.translate("Zoidberg", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.removeShaveControl.setProperty("-command", QtGui.QApplication.translate("Zoidberg", "\"removeCRCloc 1\"", None, QtGui.QApplication.UnicodeUTF8))
        self.aplyShaveControl.setText(QtGui.QApplication.translate("Zoidberg", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.aplyShaveControl.setProperty("-command", QtGui.QApplication.translate("Zoidberg", "\"removeCRCloc 0\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Zoidberg", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.ShaveQuality.setProperty("-cc", QtGui.QApplication.translate("Zoidberg", "\"setCRCAttr ShaveQuality set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.ShaveQuality.setProperty("-dc", QtGui.QApplication.translate("Zoidberg", "\"setCRCAttr ShaveQuality set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Zoidberg", "Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.Thickness.setProperty("-cc", QtGui.QApplication.translate("Zoidberg", "\"setCRCAttr Thickness set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.Thickness.setProperty("-dc", QtGui.QApplication.translate("Zoidberg", "\"setCRCAttr Thickness set\"", None, QtGui.QApplication.UnicodeUTF8))
        self.affectSegmet.setText(QtGui.QApplication.translate("Zoidberg", "Affect On Segments", None, QtGui.QApplication.UnicodeUTF8))
        self.affectSegmet.setProperty("-cc", QtGui.QApplication.translate("Zoidberg", "affectCRCSegmet", None, QtGui.QApplication.UnicodeUTF8))
        self.affectSegmet_2.setText(QtGui.QApplication.translate("Zoidberg", "Affect On Segments", None, QtGui.QApplication.UnicodeUTF8))
        self.affectSegmet_2.setProperty("-cc", QtGui.QApplication.translate("Zoidberg", "affectCRCSegmet", None, QtGui.QApplication.UnicodeUTF8))
        self.shaveControlTab.setTabText(self.shaveControlTab.indexOf(self.contolShahveTab), QtGui.QApplication.translate("Zoidberg", "Shave", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateShaveControl_4.setText(QtGui.QApplication.translate("Zoidberg", "Add Shave Control", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateShaveControl_4.setProperty("-command", QtGui.QApplication.translate("Zoidberg", "addCRCloc", None, QtGui.QApplication.UnicodeUTF8))
        self.removeShaveControl_5.setText(QtGui.QApplication.translate("Zoidberg", "Remove Shave Control", None, QtGui.QApplication.UnicodeUTF8))
        self.removeShaveControl_5.setProperty("-command", QtGui.QApplication.translate("Zoidberg", "removeCRCloc", None, QtGui.QApplication.UnicodeUTF8))
        self.shaveControlTab.setTabText(self.shaveControlTab.indexOf(self.contolShaderTab), QtGui.QApplication.translate("Zoidberg", "Shader", None, QtGui.QApplication.UnicodeUTF8))
        self.shaveControlTab.setTabText(self.shaveControlTab.indexOf(self.controlGeometryTab), QtGui.QApplication.translate("Zoidberg", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Shave_control), QtGui.QApplication.translate("Zoidberg", "Shave control", None, QtGui.QApplication.UnicodeUTF8))

